name: Generate Changelog

on:
  push:
    branches:
      - main 

permissions:
  contents: read
  pull-requests: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate Changelog
      uses: theusc6/changelog-ci@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
