name: Terraform CI

on:
  pull_request:
    paths:
      - '**.tf'
    branches:
      - main
  push:
    paths:
      - '**.tf'
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: write
  issues: write

env:
  AWS_ROLE_TO_ASSUME: ${{ secrets.DEPLOY_ROLE }}
  AWS_REGION: "us-west-2" # Modify this if you're using a different region.

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-session

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          terraform plan -out=plan.tfplan > plan_output.txt
        continue-on-error: true

      - name: Check for Plan Errors
        run: |
          if grep -q "Error:" plan_output.txt; then
            echo "Terraform plan failed. See the PR comments or the above logs for details."
            exit 1
          fi

      - name: Comment PR with Plan Result
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v3
        with:
          script: |
            var fs = require('fs');
            var output = fs.readFileSync('plan_output.txt', 'utf8');
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
